### ISSUE TITLE
PE2015.2 & CentOS 7: Service is enabled with each puppet run again

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#100]
With each puppet run, the service will be enabled again.

I have the following OS.
[root@xldeployagent ~]# cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core) 
[root@xldeployagent ~]# 

The logging is given below:
nfo: Computing checksum on file /opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml
Info: /Stage[main]/Xldeploy::Server::Security/Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]/File[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]: Filebucketed /opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml to puppet with sum acdc559102fb5f4a32a695bb1c0cf1ae
Notice: /Stage[main]/Xldeploy::Server::Security/Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]/File[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]/content: content changed '{md5}acdc559102fb5f4a32a695bb1c0cf1ae' to '{md5}a7bbb9af66692e01b6087aa4d7baa111'
Notice: /Stage[main]/Xldeploy::Server::Security/Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]/File[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]/mode: mode changed '0664' to '0640'
Notice: /Stage[main]/Xldeploy::Server::Security/Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]/File[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]/seluser: seluser changed 'unconfined_u' to 'system_u'
Info: Class[Xldeploy::Server::Security]: Scheduling refresh of Class[Xldeploy::Server::Service]
Info: Class[Xldeploy::Server::Service]: Scheduling refresh of Service[xl-deploy]
Notice: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]: Unscheduling refresh on Service[xl-deploy]
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/xldeploy-housekeeping.sh]/ensure: defined content as '{md5}12c94414fb2d81332538ba966b95de7e'
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/housekeeping.py]/ensure: defined content as '{md5}df1dcb2f8df705571ea1a2510419ff33'
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/Cron[xldeploy-housekeeping]/ensure: created
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: Applied catalog in 82.38 seconds
[root@xldeployagent ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for xldeployagent.home
Info: Applying configuration version '1445628222'
Notice: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]/enable: enable changed 'false' to 'true'
Notice: Applied catalog in 2.76 seconds
[root@xldeployagent ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for xldeployagent.home
Info: Applying configuration version '1445628237'
Notice: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]/enable: enable changed 'false' to 'true'
Notice: Applied catalog in 3.00 seconds
[root@xldeployagent ~]#

**Comment by WianVos** [comment]
in manifests/server/service : 

service { $productname:
    ensure => running,
    enable => true,
  }

I will remedy that on my next update unless superseb beats me to it

**Comment by superseb** [comment]
We have a few factors where this can be a problem:

- XL Deploy service install script supports SysV only? Or also systemd (CentOS 7)
- Puppet borks on XL Deploy service

Needs some investigating..

**Comment by ltutar** [comment]
puppet run with debug information.

Debug: Executing: '/bin/systemctl is-active xl-deploy'
Debug: Executing: '/bin/systemctl show xl-deploy --property LoadState --property UnitFileState --no-pager'
Debug: Executing: '/bin/systemctl unmask xl-deploy'
Debug: Executing: '/bin/systemctl enable xl-deploy'
Notice: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]/enable: enable changed 'false' to 'true'
Debug: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]: The container Class[Xldeploy::Server::Service] will propagate my refresh event

**Comment by ltutar** [comment]
https://tickets.puppetlabs.com/browse/PUP-5296

**Comment by superseb** [comment]
Ok, bug in Puppet provider. Should work by setting ```provider => redhat```
