### ISSUE TITLE
a time-out is needed for Xldeploy::Client

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#107]
puppet run runs like forever if the xldeploy is not available.

Info: Applying configuration version '1447169289'
Notice: /Stage[main]/Xldeploy::Client::User/Group[xldeploy]/ensure: created
Notice: /Stage[main]/Xldeploy::Client::User/User[xldeploy]/ensure: created
Notice: /Stage[main]/Xldeploy::Client::User/File[/etc/sudoers.d/50_xldeploy]/ensure: defined content as '{md5}9f4e20e6e225c1c42a7eda1ff2c0f9b4'
Notice: /Stage[main]/Logstashforwarder::Service/Logstashforwarder::Service::Init[logstash-forwarder]/Service[logstash-forwarder]/enable: enable changed 'false' to 'true'
Notice: Public key from xldeploy@wildflyagent.home@wildflyagent.home not available yet. Skipping
Notice: /Stage[main]/Xldeploy::Client::User/Sshkeys::Set_authorized_key[xldeploy@wildflyagent.home]/Notify[Public key from xldeploy@wildflyagent.home@wildflyagent.home not available yet. Skipping]/message: defined 'message' as 'Public key from xldeploy@wildflyagent.home@wildflyagent.home not available yet. Skipping'
Notice: unable to reach http://admin:xebialabs@wildflyagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebialabs@wildflyagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebialabs@wildflyagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebialabs@wildflyagent.home:4516/deployit/deployit

**Comment by WianVos** [comment]
It should be able to handel that , I'll check it out tonight

Sent from my iPhone

On 10 Nov 2015, at 10:31, Levent Tutar <notifications@github.com<mailto:notifications@github.com>> wrote:


puppet run runs like forever if the xldeploy is not available.

Info: Applying configuration version '1447169289'
Notice: /Stage[main]/Xldeploy::Client::User/Group[xldeploy]/ensure: created
Notice: /Stage[main]/Xldeploy::Client::User/User[xldeploy]/ensure: created
Notice: /Stage[main]/Xldeploy::Client::User/File[/etc/sudoers.d/50_xldeploy]/ensure: defined content as '{md5}9f4e20e6e225c1c42a7eda1ff2c0f9b4'
Notice: /Stage[main]/Logstashforwarder::Service/Logstashforwarder::Service::Init[logstash-forwarder]/Service[logstash-forwarder]/enable: enable changed 'false' to 'true'
Notice: Public key from xldeploy@wildflyagent.home@wildflyagent.home<mailto:wildflyagent.home@wildflyagent.home> not available yet. Skipping
Notice: /Stage[main]/Xldeploy::Client::User/Sshkeys::Set_authorized_key[xldeploy@wildflyagent.home<mailto:xldeploy@wildflyagent.home>]/Notify[Public key from xldeploy@wildflyagent.home@wildflyagent.home<mailto:wildflyagent.home@wildflyagent.home> not available yet. Skipping]/message: defined 'message' as 'Public key from xldeploy@wildflyagent.home@wildflyagent.home<mailto:wildflyagent.home@wildflyagent.home> not available yet. Skipping'
Notice: unable to reach http://admin:xebialabs@wildflyagent.home<mailto:xebialabs@wildflyagent.home>:4516/deployit/deployit
Notice: unable to reach http://admin:xebialabs@wildflyagent.home<mailto:xebialabs@wildflyagent.home>:4516/deployit/deployit
Notice: unable to reach http://admin:xebialabs@wildflyagent.home<mailto:xebialabs@wildflyagent.home>:4516/deployit/deployit
Notice: unable to reach http://admin:xebialabs@wildflyagent.home<mailto:xebialabs@wildflyagent.home>:4516/deployit/deployit

-

**Comment by ltutar** [comment]
ok. you can easily verify by putting the following in the yaml
xldeploy::client::cis:
  'Environments/levent':  
    'ensure': present
    'type': 'core.Directory'

make sure you have a different default value for rest_url

**Comment by superseb** [comment]
Timeout is defaulted to 240, this could be set to be more sane (like 60 seconds, why should it take longer?) or made configurable (which makes not a whole lot of sense IMHO)

**Comment by ltutar** [comment]
If XL Deploy has its repository in DB and the repo is like 40 gig. Starting XL Deploy will take like 45 minutes because it will index the data. On my small vagrant centos images, it will start in 30 seconds. That is why I want it to be configurable and also the default set to 60 seconds.

**Comment by FireDrunk** [comment]
I also noticed that during this timeout period, it's impossible to cancel the puppet run with CLTRL+C, which is quite annoying.

I think it might have something to do with the way the xldeploy class starts the underlying curl action, this probably ignores a normal SIGTERM command.

**Comment by WianVos** [comment]
this behaviour is needed because after starting xldeploy the module will continue with creating specified resources . For this action xldeploy needs to be available so the check_connection is there to make sure it is.
