### ISSUE TITLE
xldeploy_ci and other types and providers are too vague when the rest_url is incorrect

### ISSUE THREAD

**Issue by WianVos** [xebialabs/puppet-xldeploy#19]
when de xldeploy_ci type and provider are used and the rest_url is incorrect the output is very vague. 
I'm thinking of checking the url for connectivity prior to executing the rest call itself ..

**Comment by ltutar** [comment]
Also, xldeploy_ci gives OK even if the CI is not created in XL Deploy repository.

Notice: /Stage[main]/Jboss::Xldeploy/Xldeploy_ci[Infrastructure/projectx]/ensure: created
Notice: Finished catalog run in 57.21 seconds

XL Deploy logging:
2015-03-06 13:19:20.234 [qtp85192293-104] {} ERROR c.x.d.j.ClassPathResourceContentServlet - Cannot find /web/xldeploy/repository/ci/Infrastructure/projectx in classpath
2015-03-06 13:22:14.335 [qtp85192293-104] {} ERROR c.x.d.j.ClassPathResourceContentServlet - Cannot find /web/xldeploy in classpath

puppet:

# == Class jboss::xldeploy
#
# This class is called from jboss
#
class jboss::xldeploy {

  # Make this a private class
  if $caller_module_name != $module_name {
    fail("Use of private class ${name} by ${caller_module_name}")
  }

  xldeploy_ci{ 'Infrastructure/projectx':
      ensure             => present,
      type               => 'core.Directory',
      rest_url           => 'http://admin:admin1@192.168.234.10:4516/xldeploy'
   }



  anchor { 'jboss::xldeploy::begin':}
  -> Xldeploy_ci['Infrastructure/projectx']
  -> anchor { 'jboss::xldeploy::end': }
}

**Comment by ltutar** [comment]
you are right.
In my case, http://admin:admin1@192.168.234.10:4516/xldeploy should be http://admin:admin1@192.168.234.10:4516/deployit

maybe it is also handy to check if the CI is really created and then return. This is not the case now.

**Comment by WianVos** [comment]
i was right ? 
hmm .. 

I will update the ci to do a check .. 
regards

Wian
