### ISSUE TITLE
undefined method `attributes' for nil:NilClass

### ISSUE THREAD

**Issue by SmartFocusOps** [xebialabs/puppet-xldeploy#43]
Since the last update, I have a new issue: undefined method `attributes' for nil:NilClass
but as the #40 issue, I still have "change from absent to present failed" error.
I did a test with puppet 3.7.3 and ruby 1.8.7 or 1.9.3.
this is the trace for Ruby 1.9.3

[root@nlbdeployx2 ~]# puppet agent -t --trace
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for nlbdeployx2.emv2.com
Info: Applying configuration version '1418740020'
Notice: Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping
Notice: /Stage[main]/Xldeploy::Client::User/Sshkeys::Set_authorized_key[xldeploy@deployit-sandbox.emv2.com]/Notify[Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping]/message: defined 'message' as 'Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping'
Notice: /Stage[main]/Xldeploy::Client::Config/Xldeploy::Client::Config_ci[project_folder]/Xldeploy_ci[Infrastructure/PREPROD/Equinix/E0]/ensure: created
Error: Could not set 'present' on ensure: undefined method `attributes' for nil:NilClass at 45:/etc/puppet/environments/production/modules/xldeploy/manifests/client/config_ci.pp
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/xldeploy.rb:86:in `block in to_xml'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/xldeploy.rb:82:in `each'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/xldeploy.rb:82:in `to_xml'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/ci.rb:56:in `desired_xml'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/ci.rb:65:in `persist'
/var/lib/puppet/lib/puppet/provider/xldeploy_ci/rest.rb:10:in `create'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property/ensure.rb:16:in `block in defaultvalues'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property.rb:197:in `call_valuemethod'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property.rb:498:in `set'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property.rb:581:in `sync'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:204:in `sync'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:128:in `sync_if_needed'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:81:in `perform_changes'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:20:in `evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:204:in `apply'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:217:in `eval_resource'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:147:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:147:in `block (2 levels) in evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:327:in `block in thinmark'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:326:in `thinmark'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:147:in `block in evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/graph/relationship_graph.rb:118:in `traverse'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:138:in `evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/resource/catalog.rb:169:in `block in apply'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util/log.rb:149:in `with_destination'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/report.rb:112:in `as_logging_destination'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/resource/catalog.rb:168:in `apply'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:118:in `block in apply_catalog'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:161:in `block in benchmark'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:160:in `benchmark'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:117:in `apply_catalog'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:224:in `run_internal'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:132:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/context.rb:64:in `override'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet.rb:244:in `override'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:131:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:47:in `block (4 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent/locker.rb:20:in `lock'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:47:in `block (3 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:117:in `with_client'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:44:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:82:in `run_in_fork'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:43:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:179:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:179:in `controlled_run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:41:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application/agent.rb:356:in `onetime'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application/agent.rb:322:in `run_command'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:381:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:507:in `plugin_hook'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:381:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:488:in `exit_on_fail'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:381:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util/command_line.rb:146:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util/command_line.rb:92:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/bin/puppet:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/puppet:23:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/puppet:23:in `<main>'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Error: Could not set 'present' on ensure: undefined method `attributes' for nil:NilClass at 45:/etc/puppet/environments/production/modules/xldeploy/manifests/client/config_ci.pp
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/xldeploy.rb:86:in `block in to_xml'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/xldeploy.rb:82:in `each'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/xldeploy.rb:82:in `to_xml'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/ci.rb:56:in `desired_xml'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/ci.rb:65:in `persist'
/var/lib/puppet/lib/puppet/provider/xldeploy_ci/rest.rb:10:in `create'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property/ensure.rb:16:in `block in defaultvalues'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property.rb:197:in `call_valuemethod'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property.rb:498:in `set'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property.rb:581:in `sync'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:204:in `sync'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:128:in `sync_if_needed'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:81:in `perform_changes'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:20:in `evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:204:in `apply'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:217:in `eval_resource'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:147:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:147:in `block (2 levels) in evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:327:in `block in thinmark'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:326:in `thinmark'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:147:in `block in evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/graph/relationship_graph.rb:118:in `traverse'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:138:in `evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/resource/catalog.rb:169:in `block in apply'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util/log.rb:149:in `with_destination'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/report.rb:112:in `as_logging_destination'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/resource/catalog.rb:168:in `apply'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:118:in `block in apply_catalog'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:161:in `block in benchmark'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:160:in `benchmark'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:117:in `apply_catalog'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:224:in `run_internal'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:132:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/context.rb:64:in `override'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet.rb:244:in `override'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:131:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:47:in `block (4 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent/locker.rb:20:in `lock'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:47:in `block (3 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:117:in `with_client'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:44:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:82:in `run_in_fork'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:43:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:179:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:179:in `controlled_run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:41:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application/agent.rb:356:in `onetime'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application/agent.rb:322:in `run_command'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:381:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:507:in `plugin_hook'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:381:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:488:in `exit_on_fail'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:381:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util/command_line.rb:146:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util/command_line.rb:92:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/bin/puppet:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/puppet:23:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/puppet:23:in `<main>'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Wrapped exception:
undefined method `attributes' for nil:NilClass
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/xldeploy.rb:86:in `block in to_xml'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/xldeploy.rb:82:in `each'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/xldeploy.rb:82:in `to_xml'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/ci.rb:56:in `desired_xml'
/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy/ci.rb:65:in `persist'
/var/lib/puppet/lib/puppet/provider/xldeploy_ci/rest.rb:10:in `create'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property/ensure.rb:16:in `block in defaultvalues'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property.rb:197:in `call_valuemethod'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property.rb:498:in `set'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/property.rb:581:in `sync'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:204:in `sync'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:128:in `sync_if_needed'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:81:in `perform_changes'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/resource_harness.rb:20:in `evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:204:in `apply'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:217:in `eval_resource'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:147:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:147:in `block (2 levels) in evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:327:in `block in thinmark'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:326:in `thinmark'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:147:in `block in evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/graph/relationship_graph.rb:118:in `traverse'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction.rb:138:in `evaluate'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/resource/catalog.rb:169:in `block in apply'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util/log.rb:149:in `with_destination'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/transaction/report.rb:112:in `as_logging_destination'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/resource/catalog.rb:168:in `apply'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:118:in `block in apply_catalog'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:161:in `block in benchmark'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:160:in `benchmark'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:117:in `apply_catalog'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:224:in `run_internal'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:132:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/context.rb:64:in `override'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet.rb:244:in `override'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/configurer.rb:131:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:47:in `block (4 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent/locker.rb:20:in `lock'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:47:in `block (3 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:117:in `with_client'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:44:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:82:in `run_in_fork'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:43:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:179:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:179:in `controlled_run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/agent.rb:41:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application/agent.rb:356:in `onetime'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application/agent.rb:322:in `run_command'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:381:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:507:in `plugin_hook'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:381:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util.rb:488:in `exit_on_fail'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/application.rb:381:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util/command_line.rb:146:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/lib/puppet/util/command_line.rb:92:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/puppet-3.7.3/bin/puppet:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/puppet:23:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/puppet:23:in `<main>'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Error: /Stage[main]/Xldeploy::Client::Config/Xldeploy::Client::Config_ci[host]/Xldeploy_ci[Infrastructure/PREPROD/Equinix/E0/nlbdeployx2_sshHost]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `attributes' for nil:NilClass at 45:/etc/puppet/environments/production/modules/xldeploy/manifests/client/config_ci.pp
Notice: /Stage[main]/Xldeploy::Client/Anchor[xldeploy::client::end]: Dependency Xldeploy_ci[Infrastructure/PREPROD/Equinix/E0/nlbdeployx2_sshHost] has failures: true
Warning: /Stage[main]/Xldeploy::Client/Anchor[xldeploy::client::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 4.69 seconds

**Comment by WianVos** [comment]
which version of xldeploy where you using when you experienced this?

**Comment by SmartFocusOps** [comment]
Hi, we use the xldeploy 4.5 version

**Comment by bmoussaud** [comment]
@SmartFocusOps I've fixes several bugs that maybe fix your issue, can you test using the master branch?

**Comment by bmoussaud** [comment]
fixed in the documentation see commit 2235f043da56c927315feada7bab84a341067597
