### ISSUE TITLE
Make ssh key management optional 

### ISSUE THREAD

**Issue by eelcomaljaars** [xebialabs/puppet-xldeploy#48]
When trying to move from the deployit puppet module to the xldeploy puppet module, I run into the following issue : 

The XL Deploy plugin assumes it must handle SSH public key management using another puppet module, but at our site we have exitisting management of public keys that we do not want to remove. 

Can the handling of SSH keys be made optional using a parameter? 
 
The following error is blocking the usage of the new module right now. 
>
> Info: Loading facts
> in /var/opt/lib/pe-puppet/lib/facter/pe_puppetdb_server_status.rb
> Error: Could not retrieve catalog from remote server: Error 400 on
> SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError:
> Invalid resource type sshkeys::set_authorized_key
> at /etc/puppetlabs/puppet/environments/ontwikkel_hv/modules/xldeploy/manifests/client/user.pp:58 on node dftlx10148.anwb.local
> Warning: Not using cache on failed catalog
> Error: Could not retrieve catalog; skipping run
>

**Comment by WianVos** [comment]
There is now a parameter manage_keys which can be switched to false (default = true ) and guess what it does. 

It is only available for the server class for now

**Comment by eelcomaljaars** [comment]
Hi, 
I tried settings the manage keys to false like so : 

    class {xldeploy::params: manage_keys => false, }

But then puppet agent complains : 

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter manage_keys on Class[Xldeploy::Params] at /etc/puppetlabs/puppet/environments/ontwikkel_hv/site/hv_elasticsearch/manifests/elasticbase.pp:108 on node dftlx10148.anwb.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

I checked the module version for the xldeploy module but it is the latest (1.2.3.) 

Also, I need this to work with  xldeploy_ci and xldeploy::client resources.
