### ISSUE TITLE
Error xxx is not a property from 'overthere.SshHost'

### ISSUE THREAD

**Issue by SmartFocusOps** [xebialabs/puppet-xldeploy#52]
Hi,

since the last update, I have a strange issue: 
Error: '[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]:privateKeyFile' is not a property from 'overthere.SshHost'

we work with xldeploy-4.5.2, puppet-3.7.3 and ruby 1.8.7

 this is the log:
[root@nlbdeployx1 manifests]# puppet apply site.pp
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Scope(Class[Xldeploy::Client::Validation]): hosttypeoverthere.SshHostnameInfrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHostpropertiesprivateKeyFile/root/.ssh/id_rsa_opsaddressnlbdeployx1.emv2.comtagstracker2osUNIXport22passphraseOpsPa$$phras3usernamerootconnectionTypeSFTPproject_foldernameInfrastructure/PREPROD/Equinix/testtypecore.Directory
Warning: You cannot collect without storeconfigs being set on line 36 in file /etc/puppet/modules/xldeploy/manifests/client/config_ci.pp
Notice: Compiled catalog for nlbdeployx1.emv2.com in environment production in 2.63 seconds
Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
   (at /usr/lib64/ruby/gems/1.8/gems/puppet-3.7.3/lib/puppet/type/package.rb:430:in `default')
Notice: Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping
Notice: /Stage[main]/Xldeploy::Client::User/Sshkeys::Set_authorized_key[xldeploy@deployit-sandbox.emv2.com]/Notify[Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping]/message: defined 'message' as 'Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping'
Notice: /Stage[main]/Xldeploy::Client::Config/Xldeploy::Client::Config_ci[project_folder]/Xldeploy_ci[Infrastructure/PREPROD/Equinix/test]/ensure: created
Error: '[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]:privateKeyFile' is not a property from 'overthere.SshHost'
Error: /Stage[main]/Xldeploy::Client::Config/Xldeploy::Client::Config_ci[host]/Xldeploy_ci[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]/ensure: change from absent to present failed: '[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]:privateKeyFile' is not a property from 'overthere.SshHost'
Notice: /Stage[main]/Xldeploy::Client/Anchor[xldeploy::client::end]: Dependency Xldeploy_ci[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost] has failures: true
Warning: /Stage[main]/Xldeploy::Client/Anchor[xldeploy::client::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 61.57 seconds

But if I try a new one few second after, I have anoter property issue:
[root@nlbdeployx1 manifests]# puppet apply site.pp
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Scope(Class[Xldeploy::Client::Validation]): hostnameInfrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHosttypeoverthere.SshHostpropertiestagstracker2usernamerootosUNIXpassphraseOpsPa$$phras3port22privateKeyFile/root/.ssh/id_rsa_opsaddressnlbdeployx1.emv2.comconnectionTypeSFTPproject_foldernameInfrastructure/PREPROD/Equinix/testtypecore.Directory
Warning: You cannot collect without storeconfigs being set on line 36 in file /etc/puppet/modules/xldeploy/manifests/client/config_ci.pp
Notice: Compiled catalog for nlbdeployx1.emv2.com in environment production in 2.40 seconds
Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
   (at /usr/lib64/ruby/gems/1.8/gems/puppet-3.7.3/lib/puppet/type/package.rb:430:in `default')
Notice: Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping
Notice: /Stage[main]/Xldeploy::Client::User/Sshkeys::Set_authorized_key[xldeploy@deployit-sandbox.emv2.com]/Notify[Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping]/message: defined 'message' as 'Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping'
Notice: /Stage[main]/Xldeploy::Client::Config/Xldeploy::Client::Config_ci[project_folder]/Xldeploy_ci[Infrastructure/PREPROD/Equinix/test]/ensure: created
Error: '[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]:tags' is not a property from 'overthere.SshHost'
Error: /Stage[main]/Xldeploy::Client::Config/Xldeploy::Client::Config_ci[host]/Xldeploy_ci[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]/ensure: change from absent to present failed: '[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]:tags' is not a property from 'overthere.SshHost'
Notice: /Stage[main]/Xldeploy::Client/Anchor[xldeploy::client::end]: Dependency Xldeploy_ci[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost] has failures: true
Warning: /Stage[main]/Xldeploy::Client/Anchor[xldeploy::client::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 4.53 seconds

and another one if I test again:
[root@nlbdeployx1 manifests]# puppet apply site.pp
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Scope(Class[Xldeploy::Client::Validation]): project_foldernameInfrastructure/PREPROD/Equinix/testtypecore.Directoryhosttypeoverthere.SshHostnameInfrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHostpropertiesusernamerootconnectionTypeSFTPpassphraseOpsPa$$phras3port22privateKeyFile/root/.ssh/id_rsa_opsaddressnlbdeployx1.emv2.comtagstracker2osUNIX
Warning: You cannot collect without storeconfigs being set on line 36 in file /etc/puppet/modules/xldeploy/manifests/client/config_ci.pp
Notice: Compiled catalog for nlbdeployx1.emv2.com in environment production in 2.48 seconds
Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
   (at /usr/lib64/ruby/gems/1.8/gems/puppet-3.7.3/lib/puppet/type/package.rb:430:in `default')
Notice: Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping
Notice: /Stage[main]/Xldeploy::Client::User/Sshkeys::Set_authorized_key[xldeploy@deployit-sandbox.emv2.com]/Notify[Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping]/message: defined 'message' as 'Public key from xldeploy@deployit-sandbox.emv2.com@deployit-sandbox.emv2.com not available yet. Skipping'
Notice: /Stage[main]/Xldeploy::Client::Config/Xldeploy::Client::Config_ci[project_folder]/Xldeploy_ci[Infrastructure/PREPROD/Equinix/test]/ensure: created
Error: '[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]:username' is not a property from 'overthere.SshHost'
Error: /Stage[main]/Xldeploy::Client::Config/Xldeploy::Client::Config_ci[host]/Xldeploy_ci[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]/ensure: change from absent to present failed: '[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost]:username' is not a property from 'overthere.SshHost'
Notice: /Stage[main]/Xldeploy::Client/Anchor[xldeploy::client::end]: Dependency Xldeploy_ci[Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost] has failures: true
Warning: /Stage[main]/Xldeploy::Client/Anchor[xldeploy::client::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 6.44 seconds

I check my site.pp to be sure there is no syntax error.
Let me know any other information you think might be helpful.

**Comment by bmoussaud** [comment]
@SmartFocusOps this error is now raised during the xml serialization to help the user in case of misspelled properties. Can you post the xdelploy_ci puppet definition of 'Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost' CI ?

**Comment by SmartFocusOps** [comment]
this is:

cis => { 'project_folder' => { name => "Infrastructure/PREPROD/Equinix/test",
                                   type => 'core.Directory',
                                },
             'host' => { name => "Infrastructure/PREPROD/Equinix/test/nlbdeployx1_sshHost",
                         type => 'overthere.SshHost',
                         properties => { 'os' => 'UNIX',
                                         'connectionType' => 'SFTP',
                                         'address' => 'nlbdeployx1.emv2.com',
                                         'port' => 22,
                                         'username' => 'root',
                                         'privateKeyFile' => '/root/.ssh/id_rsa_ops',
                                         'passphrase' => 'xxx',
                                         'tags' => 'tracker2',
                         }
             }
    }

**Comment by hierynomus** [comment]
Which version of overthere are you using? privateKeyFile is newly added and is not in any released XL product.

**Comment by SmartFocusOps** [comment]
I tired to use the properties in this doc https://docs.xebialabs.com/xl-deploy/4.5.x/remotingPluginManual.html

**Comment by bmoussaud** [comment]
@SmartFocusOps instead to declare your ci using a pretty old fashioned style 
````
class{xldeploy::client:
..
cis    => '....'
}
````

can you tried to use directly the xldeploy_ci syntax used in the following sample : https://github.com/bmoussaud/xl-deploy-puppet-sample/blob/master/puppet/modules/xld-base/manifests/init.pp

**Comment by WianVos** [comment]
i've been investigating this error .. 
@hierynomus privateKeyFile has been a property of the overthere.SshHost ci for as long as i can remember and i should not be causing any problems . 
@SmartFocusOps can you try a simple rest call to the xldeploy metadataservice like : 
http://user:password@your.xldeploy.server:4516/deployit/metadata/type/overthere.SshHost and check wether the privateKeyFile comes back as a property?

**Comment by SmartFocusOps** [comment]
Hi,
I check the metadata on my side and the privateKeyFile is well as a property.

**Comment by WianVos** [comment]
could you do a puppet run with the --trace option ?

**Comment by bmoussaud** [comment]
I had a call with  @smartfocusops : they'll try to use the xldeploy_ci directly because they have not need to setup a cli on the remote mode : need to improve the documentation

**Comment by bmoussaud** [comment]
fixed in the documentation see commit 2235f043da56c927315feada7bab84a341067597

**Comment by WianVos** [comment]
Thnx Benoit



Sent from my iPhone

On 21 Jan 2015, at 09:05, Benoit Moussaud <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #52<https://github.com/xebialabs/puppet-xldeploy/issues/52>.

-
