### ISSUE TITLE
order dictionary list

### ISSUE THREAD

**Issue by SmartFocusOps** [xebialabs/puppet-xldeploy#53]
Hi,
I use this resource  to add the dictionary of my new host in the list of my environment:

xldeploy_environment_member { "Manage Dico of $env_path":
    env                => "$env_path",
    members    => ["$infra_folder/$hostname","$infra_folder/$hostname/$hostname-tomcat ", "$infra_folder/$hostname/$hostname-tomcat/$hostname-tomcat.vh ","$infra_folder/$hostname/$hostname-apache","$infra_folder/$hostname/$hostname-firewall"],
    dictionaries => ["$dico_folder/$hostname"],
    rest_url        => "$xldeploy_rest_url",
  }

But my issue is the dictionary is added at the end of the list (after a common dictionary for example).
Is there an option to order the list, to add new dictionary in first ?

Regards.

**Comment by WianVos** [comment]
i don't believe there is . I'll have to look in to it ..

**Comment by ltutar** [comment]
I also would like to have this option. Info from documentation:
Dictionaries are evaluated in the order in which they appear in the GUI. The first dictionary that defines a value for a placeholder is the one that XL Deploy uses for that placeholder.

**Comment by WianVos** [comment]
I've tested this and the dictionaries actually appear in the order they where presented to puppet. I guess the way to fix your perticular problem is to have puppet add all the dictionaries
