### ISSUE TITLE
Puppet says that the CI is created but in fact it is not.

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#55]
I have the following puppet code:
  xldeploy_environment_member{ "MyUniqueID":
    env     => "Environments/MyEnv",
    members => ["Infrastructure/projectx/agentcentos_sshHost"
    ],
    dictionaries => ["Environments/mydictionary"
    ],
  }

I see the following logging after the puppet agent -t run

Notice: /Stage[main]/Jboss_wrapper::Xldeploy/Xldeploy_environment_member[MyUniqueID]/ensure: created
Notice: Finished catalog run in 37.84 seconds

and I see the following logging in XL Deploy
2015-03-09 10:36:59.667 [qtp85192293-339] {username=admin} INFO  c.x.deployit.DeployitExceptionMapper - Intercepting DeployitException
com.xebialabs.deployit.exception.NotFoundException: Repository entity [Environments/mydictionary] not found
  at com.xebialabs.deployit.repository.JcrRepositoryService$2.doInJcr(JcrRepositoryService.java:113) ~[appserver-core-2014.7.5.jar:na]

I expected the puppet run fail since the CI is not created in XL Deploy repository. I am now not able to keep the puppet run and XL Deploy repository in sync since puppet always gives an OK.

**Comment by WianVos** [comment]
fixed
