### ISSUE TITLE
puppet run complains about XXX is not a property from XXX

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#56]
Hi,

I keep getting issues with failed: '[Environments/Development/InfraDictionaries/infra-dictionary]:members' is not a property from 'udm.Dictionary'

or 

Notice: /Stage[main]/Xldeploy_generic::Config/Notify[environment_initial_and_number: D04]/message: defined 'message' as 'environment_initial_and_number: D04'
Error: '[Environments/Development/D04]:entries' is not a property from 'core.Directory'
Error: /Stage[main]/Xldeploy_generic::Config/Xldeploy_ci[Environments/Development/D04]/ensure: change from absent to present failed: '[Environments/Development/D04]:entries' is not a property from 'core.Directory'

The first CI other than core.Directory works OK. The second does not.

For example. Environment CI works but Dictionary not.  I can not make more sense out of it.
  xldeploy_ci{ "Environments/${environment_name}/${environment_initial_and_number}":
      ensure             => present,
      type               => 'core.Directory',
  }

  xldeploy_ci{ "Environments/${environment_name}/InfraDictionaries":
      ensure             => present,
      type               => 'core.Directory',
  }

  xldeploy_ci{ "Environments/${environment_name}/${environment_initial_and_number}/${environment_initial_and_number}-environment":
      ensure             => present,
      type               => 'udm.Environment',
  }

  xldeploy_ci{ "Environments/${environment_name}/InfraDictionaries/infra-dictionary":
      ensure             => present,
      type               => 'udm.Dictionary',
  }

**Comment by ltutar** [comment]
The first run:
Notice: /Stage[main]/Xldeploy_generic::Simple/Xldeploy_ci[Environments/A]/ensure: created
Notice: /Stage[main]/Xldeploy_generic::Simple/Xldeploy_ci[Environments/A/InfraDictionaries]/ensure: created
Notice: /Stage[main]/Xldeploy_generic::Simple/Xldeploy_ci[Environments/A/InfraDictionaries/infra-dictionary]/ensure: created
Notice: /Stage[main]/Xldeploy_generic::Simple/Xldeploy_ci[Environments/A/InfraDictionaries/infra-dictionary-encrypted]/ensure: created
Notice: /Stage[main]/Xldeploy_generic::Simple/Xldeploy_ci[Environments/A/A-environment]/ensure: created

The second run:
Error: '[Environments/A/A-environment]:entries' is not a property from 'udm.Environment'
Error: /Stage[main]/Xldeploy_generic::Simple/Xldeploy_ci[Environments/A/A-environment]/properties: change from {"dictionaries"=>[], "members"=>[], "triggers"=>[]} to {"dictionaries"=>[], "entries"=>{}, "members"=>[], "triggers"=>[]} failed: '[Environments/A/A-environment]:entries' is not a property from 'udm.Environment'
Notice: /Stage[main]/Xldeploy_generic::Simple/Anchor[xldeploy_generic::simple::end]: Dependency Xldeploy_ci[Environments/A/A-environment] has failures: true
Warning: /Stage[main]/Xldeploy_generic::Simple/Anchor[xldeploy_generic::simple::end]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy_generic::Config/Anchor[xldeploy_generic::config::begin]: Dependency Xldeploy_ci[Environments/A/A-environment] has failures: true
Warning: /Stage[main]/Xldeploy_generic::Config/Anchor[xldeploy_generic::config::begin]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy_generic::Config/Notify[environment_initial_and_number:D04]: Dependency Xldeploy_ci[Environments/A/A-environment] has failures: true

**Comment by ltutar** [comment]
It seems as if the code is using the properties of the previous CI in the new CI.

'[Environments/A/A-environment]:entries' is not a property from 'udm.Environment'

entries is a property of udm.EncryptedDictionary and it is looking for it in udm.Environment

**Comment by ltutar** [comment]
It looks like I am not able to create an emtpy environment with xldepoy_ci as shown below:
  xldeploy_ci{ "Environments/${environment_name}/${environment_initial_and_number}/${environment_initial_and_number}-environment":
      ensure             => present,
      type               => 'udm.Environment',
  }

It does work if I use the following:
  xldeploy_environment_member{ "Environments/${environment_name}/${environment_initial_and_number}/${environment_initial_and_number}-environment":
    env     => "Environments/${environment_name}/${environment_initial_and_number}/${environment_initial_and_number}-environment",
    members => [ ],
    dictionaries => [ ],
  }

**Comment by ltutar** [comment]
spoke too soon. still have the issue.
Error: '[Environments/Development/InfraDictionaries]:entries' is not a property from 'core.Directory'
Error: /Stage[main]/Xldeploy_generic::Config/Xldeploy_ci[Environments/Development/InfraDictionaries]/properties: change from {} to {"entries"=>{}} failed: '[Environments/Development/InfraDictionaries]:entries' is not a property from 'core.Directory'

**Comment by WianVos** [comment]
it looks like it's trying to access a directory as being a dictionary .. which is strange .. 

can u mail me a copy of your code ?

**Comment by WianVos** [comment]
i've been testing this .. and as it turns out the error only occurs when the environment ci is setup with no properties. 

I will look into this further

**Comment by bmoussaud** [comment]
I've seen this issue when a call to API is made during the startup of the XLD server, it is responding but it is not available: if you re rerun the puppet manifest it is ok.. isn't it ?
