### ISSUE TITLE
xldeploy_environment_member gives missing end tag if XL Deploy is not running 

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#57]
If xldeploy server is not running, the xldeploy_environment_member  gives the following error:

Error: /Stage[main]/Xldeploy_generic::Config/Xldeploy_environment_member[Environments/Development/D04/D04-environment]: Could not evaluate: #<REXML::ParseException: Missing end tag for 'hr' (got "body")
Line: 10
Position: 384
Last 80 unconsumed characters:
>

xldeploy_ci is giving ok as stated in a different issue

**Comment by WianVos** [comment]
This is now fixed .. the rest part of the library will raise an error if the host is not reachable
