### ISSUE TITLE
Invalid parameter ensure on Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#62]
I have the following modules:

[root@puppetmaster puppet]# puppet module list
/etc/puppetlabs/puppet/modules
├── dalen-puppetdbquery (v1.5.3)
├── jboss (???)
├── jboss_wrapper (???)
├── jdk (???)
├── jtopjian-sshkeys (v0.5.0)
├── puppetlabs-pe_gem (v0.1.0)
├── urandom (???)
└── xldeploy (???)
/opt/puppet/share/puppet/modules
├── puppetlabs-apt (v1.5.0)
├── puppetlabs-auth_conf (v0.2.2)
├── puppetlabs-concat (v1.0.4)
├── puppetlabs-firewall (v1.1.2)
├── puppetlabs-inifile (v1.1.0)
├── puppetlabs-java_ks (v1.2.4)
├── puppetlabs-pe_accounts (v2.0.2-3-ge71b5a0)
├── puppetlabs-pe_console_prune (v0.1.1-4-g293f45b)
├── puppetlabs-pe_mcollective (v0.2.10-15-gb8343bb)
├── puppetlabs-pe_postgresql (v1.0.4-4-g0bcffae)
├── puppetlabs-pe_puppetdb (v1.1.1-13-gddf24c2)
├── puppetlabs-pe_razor (v0.2.1-1-g80acb4d)
├── puppetlabs-pe_repo (v0.7.7-32-gfd1c97f)
├── puppetlabs-pe_staging (v0.3.3-2-g3ed56f8)
├── puppetlabs-postgresql (v2.5.0-pe2)
├── puppetlabs-puppet_enterprise (v3.2.1-27-g8f61956)
├── puppetlabs-reboot (v0.1.4)
├── puppetlabs-request_manager (v0.1.1)
└── puppetlabs-stdlib (v4.5.1)

Confirming to Modulefile as stated:
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'dalen/puppetdbquery', '>= 1.4.0'
dependency 'jtopjian/sshkeys', '0.5.0'
dependency 'puppetlabs/pe_gem', '>= 0.1.0'

When I run xldeploy::server after installing xldeploy, I get the following error:
[root@puppetagent ssl]# puppet agent -t
Info: Retrieving plugin
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/iptables_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/pe_postgres_default_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/postgres_default_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/root_home.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/pe_puppetdb_server_status.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/xldeploy_facts.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/custom_auth_conf.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/concat_basedir.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/windows.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/puppet_vardir.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/sshpubkey.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/ip6tables_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/pe_build.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/pe_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/staging_http_get.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/iptables_persistent_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/platform_tag.rb
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter ensure on Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml] at /etc/puppetlabs/puppet/modules/xldeploy/manifests/server/security.pp:37 on node puppetagent.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
[root@puppetagent ssl]# 

This can be related to issue 23 which was closed.

**Comment by WianVos** [comment]
i've been looking at this , but i can't reproduce it .. 

which version of the module are u running ? 
what parameters are u using to call the module ?

**Comment by ltutar** [comment]
I downloaded the master.
I did not fill any parameters. just added the xldeploy::server and run it

**Comment by WianVos** [comment]
i'll try that

**Comment by WianVos** [comment]
as it seems this happens when u use an old version of the concat module. 
Please try and upgrade to 1.1.0 of the puppetlabs-concat version of things. 

That should fix it .

**Comment by WianVos** [comment]
i also did the update in the Modulefile and the metadata.json only available on github for now

**Comment by ltutar** [comment]
Yes. It did. Thank you for your time. 

Notice: Upgrading -- do not interrupt ...
/opt/puppet/share/puppet/modules
└── puppetlabs-concat (v1.0.4 -> v1.2.0)

**Comment by ltutar** [comment]
I'll close the issue.

**Comment by ltutar** [comment]
I'll close the issue.
