### ISSUE TITLE
community edition will not install

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#64]
I try to install the community edition of xldeploy version 4.5.3 by setting the parameter xld_community_edition to true in params.pp. If this parameter is set to false, then it works.

After the first puppet run, I get the following error.

Info: Class[Xldeploy::Server::Security]: Scheduling refresh of Class[Xldeploy::Server::Service]
Info: Class[Xldeploy::Server::Service]: Scheduling refresh of Service[xl-deploy]
Notice: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]: Unscheduling refresh on Service[xl-deploy]
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/xldeploy-housekeeping.sh]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/xldeploy-housekeeping.sh]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/garbage-collector.py]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/garbage-collector.py]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/housekeeping.py]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/housekeeping.py]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/Cron[xldeploy-housekeeping]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Housekeeping/Cron[xldeploy-housekeeping]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server::Post_config/Xldeploy_check_connection[default]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Post_config/Xldeploy_check_connection[default]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server/Anchor[xldeploy::server::end]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server/Anchor[xldeploy::server::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 172.97 seconds

After the second puppet run, I get the following error:

Info: Applying configuration version '1429047744'
Notice: /Stage[main]/Xldeploy::Server::Install/Notify[xld_community_edition true]/message: xld_community_edition true
Notice: /Stage[main]/Xldeploy::Server::Install/Notify[xld_community_edition true]/message: defined 'message' as 'xld_community_edition true'
Error: Cannot create /opt/xl-deploy/xl-deploy-cli/ext; parent directory /opt/xl-deploy/xl-deploy-cli does not exist
Error: /Stage[main]/Xldeploy::Cli::Install/File[xldeploy cli ext]/ensure: change from absent to directory failed: Cannot create /opt/xl-deploy/xl-deploy-cli/ext; parent directory /opt/xl-deploy/xl-deploy-cli does not exist
Notice: /Stage[main]/Xldeploy::Cli::Install/Anchor[cli::installend]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Cli::Install/Anchor[cli::installend]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Cli/Anchor[xldeploy::cli::end]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Cli/Anchor[xldeploy::cli::end]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server::Config/Ini_setting[xldeploy.admin.password]/value: value changed '{b64}YaQTz9tcOkhITTCIpCEcra2KbByBTwXWZRIdwplcFzg\=' to '{b64}rBeGnO+rWpx4xPyC+C+B6A=='
Notice: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]: Unscheduling refresh on Service[xl-deploy]
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/xldeploy-housekeeping.sh]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/xldeploy-housekeeping.sh]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/garbage-collector.py]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/garbage-collector.py]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/housekeeping.py]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Housekeeping/File[/opt/xl-deploy/xl-deploy-server/scripts/housekeeping.py]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server::Housekeeping/Cron[xldeploy-housekeeping]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Housekeeping/Cron[xldeploy-housekeeping]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server::Post_config/Xldeploy_check_connection[default]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server::Post_config/Xldeploy_check_connection[default]: Skipping because of failed dependencies
Notice: /Stage[main]/Xldeploy::Server/Anchor[xldeploy::server::end]: Dependency File[xldeploy cli ext] has failures: true
Warning: /Stage[main]/Xldeploy::Server/Anchor[xldeploy::server::end]: Skipping because of failed dependencies
Notice: Finished catalog run in 5.66 seconds

FYI. the download_user and download_password are filled in with correct values.

**Comment by ltutar** [comment]
I see the problem. I tell in params.pp that I want to install 4.5.3 but cli version 4.5.2 will be downloaded and the symbolic link is not working then.

[root@puppetagent xl-deploy]# ls -al
total 16
drwxr-xr-x.  4 xldeploy xldeploy 4096 Apr 14 23:40 .
drwxr-xr-x.  5 root     root     4096 Apr 14 23:38 ..
drwxr-xr-x.  8 xldeploy xldeploy 4096 Nov  5 11:05 xl-deploy-4.5.2-cli-free-edition
drwxr-xr-x. 15 xldeploy xldeploy 4096 Apr 14 23:40 xl-deploy-4.5.3-server-free-edition
lrwxrwxrwx.  1 xldeploy xldeploy   47 Apr 14 23:40 xl-deploy-cli -> /opt/xl-deploy/xl-deploy-4.5.3-cli-free-edition
lrwxrwxrwx.  1 xldeploy xldeploy   50 Apr 14 23:39 xl-deploy-server -> /opt/xl-deploy/xl-deploy-4.5.3-server-free-edition
[root@puppetagent xl-deploy]#

**Comment by ltutar** [comment]
and in cli.pp, you have the following:
 #we need to support the two different download urls for xldeploy and deployit
    if ($custom_download_cli_url == undef) {
      if str2bool($xld_community_edition) {
        $download_cli_url    = "https://download.xebialabs.com/files/Generic/xl-deploy-4.5.2-cli-free-edition.zip"
where 4.5.2 is hardcoded. Can you replace it with ${version} please?
server.pp seems to be OK.

**Comment by WianVos** [comment]
Can you correct this and do a pull request ?

Sent from my iPhone

On 14 Apr 2015, at 17:55, Levent Tutar <notifications@github.com<mailto:notifications@github.com>> wrote:


and in cli.pp, you have the following:
#we need to support the two different download urls for xldeploy and deployit
if ($custom_download_cli_url == undef) {
if str2bool($xld_community_edition) {
$download_cli_url = "https://download.xebialabs.com/files/Generic/xl-deploy-4.5.2-cli-free-edition.zip"
where 4.5.2 is hardcoded. Can you replace it with ${version} please?
server.pp seems to be OK.

-

**Comment by ltutar** [comment]
I hope it went ok.

https://github.com/xebialabs/puppet-xldeploy/pull/66

Met vriendelijke groet,

Levent


Levent Tutar * Senior Consultant
Xebia BV * Utrechtseweg 49 * 1213 TL Hilversum * The Netherlands
mobile +31 641452164  * office +31 35 5381921 * email ltutar@xebia.com

Visit Xebia on web at  www.xebia.com

On 15 Apr 2015, at 00:51, WianVos <notifications@github.com> wrote:

Can you correct this and do a pull request ?

Sent from my iPhone

On 14 Apr 2015, at 17:55, Levent Tutar <notifications@github.com<mailto:notifications@github.com>> wrote:


and in cli.pp, you have the following:
#we need to support the two different download urls for xldeploy and deployit
if ($custom_download_cli_url == undef) {
if str2bool($xld_community_edition) {
$download_cli_url = "https://download.xebialabs.com/files/Generic/xl-deploy-4.5.2-cli-free-edition.zip"
where 4.5.2 is hardcoded. Can you replace it with ${version} please?
server.pp seems to be OK.

-

**Comment by WianVos** [comment]
fixed in master branch
