### ISSUE TITLE
feature request: supply the license file instead of downloading it every time via internet

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#65]
Is it possible to add the feature of supplying the license file? At this moment it will be downloaded. This is not working if there is no internet connection or valid download username and password during the installation.

**Comment by ltutar** [comment]
my bad

**Comment by WianVos** [comment]
i have a terrible memory .. but as it turns out .. this feature was already in the module .. just specifiy a puppetfiles file source to the custom_license_source parameter and it will get the license file from puppetfiles instead of downloading it

**Comment by ltutar** [comment]
Yes, but the problem is that the property   $custom_license_source is set to undef in server.pp.
There is no relationship of this property with params.pp where you configure and define things.

**Comment by WianVos** [comment]
You NEVER edit the params.pp to modify module behaviour specific to your customer site. params.pp holds defaults not customization. You specify your custom parameters at class invocation. 

for example:
class{'xldeploy-server':
  custom_download_server_url => 'puppet:///do/not/edit/params.pp/xldeploy.zip',
  custom_license_source          => 'puppet:///never/shall/i/edit/params.pp/deployit-license.lic'
  version                                    => '4.5.1'
}

now class parameters that do not require a default are not in the params.pp

**Comment by ltutar** [comment]
I do edit the params.pp and not use parameters at class invocation. My intention is to replace all the values in params.pp later with hiera.
That is why I want this property to be exposed in params.pp.
A part of my jboss params.pp is shown below:
class jboss::params {
  case $::osfamily {
    'RedHat': {
      $jboss_unix_group                    = hiera('jboss_unix_group')
      $jboss_unix_group_gid                = hiera('jboss_unix_group_gid')
      $jboss_unix_user                     = hiera('jboss_unix_user')
      $jboss_unix_user_gid                 = hiera('jboss_unix_user_gid')
      $jboss_home_dir                      = hiera('jboss_home_dir')

**Comment by WianVos** [comment]
no no no NO
You are doing it wrong. !!!!!!!!!

please listen to me .. !!!!!!!!!!!

please do not edit the params.pp .. do not .. under no circumstance

if u want to use hiera use the way puppet recommends it .. by means of automatic parameter lookup 

here is the documentation : https://docs.puppetlabs.com/hiera/1/puppet.html#automatic-parameter-lookup

please read it !!!!!!!!!!!

**Comment by ltutar** [comment]
Thanks Wian. Your solution works. I do not need to edit params.pp.
