### ISSUE TITLE
feature request: supply database drivers through file instead of download

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#68]
Just like the following:
custom_download_server_url: 'puppet:///modules/xldeploy/sources/xl-deploy-4.5.3-server.zip'
or 
custom_license_source: 'puppet:///modules/xldeploy/license/deployit-license.lic'

I also would like to supply the database drivers through 
datastore_jdbc_driver_url: 'puppet:///modules/xldeploy/lib/mysql-connector-java-5.1.35-bin.jar'
or as a directory
datastore_jdbc_driver_url: 'puppet:///modules/xldeploy/lib'

**Comment by WianVos** [comment]
wilco

**Comment by ltutar** [comment]
??

**Comment by WianVos** [comment]
done .. 

You can now specify a puppet: url for datastore_jdbc_driver_url
