### ISSUE TITLE
feature request: cluster id set to hostname and remove cluster role

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#73]
1) The clustered jackrabbit repository configuration i.e. jackrabbit-repository-db-mysql-cluster.xml.erb is used when $xldeploy_cluster_id != undef in repository.xml.
When you set this cluster id to a value, also the passive gets this value.

Since the cluster erb contains:
<Cluster id="<%= @xldeploy_cluster_id %>" syncDelay="2000">
Please change it to:
<Cluster id="<%= @hostname %>" syncDelay="2000">
2) I removed the whole if - else statement in repository.pp

  if $xldeploy_cluster_id != undef {
    case $xldeploy_cluster_role {

And active/passive was working perfectly with mysql. (After editing the files mentioned in the issued of tonight)

note: because of special characters, the code is not seen. Click on update comment to see it. 
Just use hostname as cluster id with 'AT' character in front of it.

**Comment by ltutar** [comment]
maybe also better to use xldeploy_use_cluster (booelan) instead of  xldeploy_cluster_id. xldeploy_cluster_id  has no use since I want to use hostname as cluster id

**Comment by WianVos** [comment]
cluster id removed .. changed to hostname as requested
