### ISSUE TITLE
feature request: Audit in database

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#74]
The following snippet is from the default logback.xml:
   

    <appender name="AUDIT" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>log/audit.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <FileNamePattern>log/audit.%d{yyyy-MM-dd}.log</FileNamePattern>
        </rollingPolicy>
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%logger{36}] %msg%n</pattern>
        </encoder>
    </appender>

    <logger name="audit" level="info" additivity="false">
        <appender-ref ref="AUDIT" />
    </logger>

It is also possible to write the AUDIT to database. An example is given below:

    

    <appender name="AUDIT" class="ch.qos.logback.classic.db.DBAppender">
        <connectionSource class="ch.qos.logback.core.db.DataSourceConnectionSource">
            <dataSource class="com.mchange.v2.c3p0.ComboPooledDataSource">
                <driverClass>oracle.jdbc.driver.OracleDriver</driverClass>
                <jdbcUrl>jdbc:oracle:thin:@ldap://oidsrvr1.robeco.nl:389/ODIT,cn=OracleContext,dc=world</jdbcUrl>
                <user>dbadity</user>
                <password>dbadity</password>
            </dataSource>
        </connectionSource>
    </appender>

See http://logback.qos.ch/manual/appenders.html#DBAppender for more information.

**Comment by WianVos** [comment]
Levent .. 

Could you find out what the correct code snippets for postgresql and mysql would be ?

**Comment by ltutar** [comment]
Yes. I will have look at it this weekend and let you know.
