### ISSUE TITLE
reintroduce the ability to drive a deployment

### ISSUE THREAD

**Issue by gthomas258** [xebialabs/puppet-xldeploy#79]
Hello,

we are former users of this plugin, especially for its ability to drive a deployment between an application version and an environment iD.

is it planned soon to reintroduce this feature present in the old module version?

Regards,
Guillaume

**Comment by WianVos** [comment]
which version of this module was able to do a deployment ?

**Comment by WianVos** [comment]
Deployments are not a planned and will not be as far as i am concerned ..
