### ISSUE TITLE
PE 2015.2 & XLD 5.1 - deployit-security.xml]: Triggered 'refresh' from 1 events

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#94]
I downloaded the latest master tonight. 

With each puppet run, the XLD is restarted again because of 
Notice: /Stage[main]/Xldeploy::Server::Security/Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]/Exec[concat_/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]: Triggered 'refresh' from 1 events

more logging is shown below:
[root@xldeployagent ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for xldeployagent.home
Info: Applying configuration version '1445544002'
Notice: /Stage[main]/Xldeploy::Server::Config/File[/opt/xl-deploy/xl-deploy-server/hotfix/lib]: Not removing directory; use 'force' to override
Notice: /Stage[main]/Xldeploy::Server::Config/File[/opt/xl-deploy/xl-deploy-server/hotfix/lib]/ensure: removed
Notice: /Stage[main]/Xldeploy::Server::Config/File[/opt/xl-deploy/xl-deploy-server/hotfix/plugins]: Not removing directory; use 'force' to override
Notice: /Stage[main]/Xldeploy::Server::Config/File[/opt/xl-deploy/xl-deploy-server/hotfix/plugins]/ensure: removed
Notice: /Stage[main]/Xldeploy::Server::Config/Exec[/bin/echo xldeploy|/opt/xl-deploy/xl-deploy-server/bin/install-service.sh]/returns: executed successfully
Info: Class[Xldeploy::Server::Config]: Scheduling refresh of Class[Xldeploy::Server::Security]
Info: Class[Xldeploy::Server::Security]: Scheduling refresh of Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]
Info: Class[Xldeploy::Server::Security]: Scheduling refresh of Concat::Fragment[security_header]
Info: Class[Xldeploy::Server::Security]: Scheduling refresh of Concat::Fragment[httpsecurity]
Info: Class[Xldeploy::Server::Security]: Scheduling refresh of Concat::Fragment[security_footer]
Info: Class[Xldeploy::Server::Security]: Scheduling refresh of Concat::Fragment[security_beans]
Info: Class[Xldeploy::Server::Security]: Scheduling refresh of Concat::Fragment[security_authentication_manager]
Info: Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]: Scheduling refresh of Exec[concat_/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]
Notice: /Stage[main]/Xldeploy::Server::Security/Concat[/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]/Exec[concat_/opt/xl-deploy/xl-deploy-server/conf/deployit-security.xml]: Triggered 'refresh' from 1 events
Info: Class[Xldeploy::Server::Security]: Scheduling refresh of Class[Xldeploy::Server::Service]
Info: Class[Xldeploy::Server::Service]: Scheduling refresh of Service[xl-deploy]
Notice: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Xldeploy::Server::Service/Service[xl-deploy]: Unscheduling refresh on Service[xl-deploy]
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: unable to reach http://admin:xebia1@xldeployagent.home:4516/deployit/deployit 
Notice: Applied catalog in 41.98 seconds
[root@xldeployagent ~]#

**Comment by WianVos** [comment]
this is covered by issue #100
