### ISSUE TITLE
The password is shown in clear text

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#96]
The first run shows the following.

Notice: /Stage[main]/Xldeploy::Server::Config/Ini_setting[xldeploy.admin.password]/value: value changed '{b64}TRcRslO2oRjZ+PpmIoMEzw\=\=' to 'xebia1'

**Comment by WianVos** [comment]
I know .. The only way to remedy that is to put the password in hiera encoded

Sent from my iPhone

On 22 Oct 2015, at 16:21, Levent Tutar <notifications@github.com<mailto:notifications@github.com>> wrote:


The first run shows the following.

Notice: /Stage[main]/Xldeploy::Server::Config/Ini_setting[xldeploy.admin.password]/value: value changed '{b64}TRcRslO2oRjZ+PpmIoMEzw\=\=' to 'xebia1'

-
